version: '3.8'

services:
  # Service 1: repo_nha_hang_com_ga_BE
  repo-service:
    image: haibui040623/repo-nha-hang-com-ga-be:latest
    container_name: repo-nha-hang-com-ga-be-container
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb= ${{ secrets.MONGODB_CONNECTIONSTRING }}
    networks:
      - mynetwork

  # Service 2: Auth Service
  auth-service:
    image: haibui040623/auth-service:latest
    container_name: auth-service-container
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb= ${{ secrets.MONGODB_CONNECTIONSTRING }}
    networks:
      - mynetwork

  # Service 3: File Service
  file-service:
    image: haibui040623/file-service:latest
    container_name: file-service-container
    ports:
      - "8082:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb= ${{ secrets.MONGODB_CONNECTIONSTRING }}
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
