version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db # Lưu trữ dữ liệu MongoDB tránh mất khi container restart

  backend:
    image: repo-nha-hang-com-ga-be
    container_name: repo-nha-hang-com-ga-be-container
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__MongoDb: "mongodb://admin:admin123@52.64.190.146:27017"

volumes:
  mongo_data:
